---
- name: make sure the MySQL users are present
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default('pass') }}"
    priv: "{{ item.priv | default('*.*:ALL') }}"
    state: present
    host: "{{ item.host | default('localhost') }}"
  with_items: mariadb_users
  when: mariadb_users | length > 0
