---
- name: Install java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: install tomcat
  yum: name=tomcat

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: configure tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf
  notify: restart tomcat

- name: configure tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf
  notify: restart tomcat

- name: start tomcat
  service: name=tomcat state=started enabled=yes

- name: deploy iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: insert firewalld rule for tomcat http port
  firewalld: port={{ tomcat_port }}/tcp permanent=true state=enabled immediate=yes
 
- name: wait for tomcat to start
  wait_for: port={{ tomcat_port }}   
